### ISSUE TITLE
readme 有段写错了

### ISSUE THREAD

**Issue by xcheng5787** [purgeteam/unified-dispose-springboot#1]
**Describe the bug**
ReadMe指导使用自定义Excption继承 BusinessException的时候 使用UserException 枚举里面有点错误

**To Reproduce**

@Getter
public enum UserErrorCode {
    /**
     * 权限异常
     */
    NOT_PERMISSIONS("CLOUD401","您没有操作权限"),
    ;

    private String code;

    private String message;

    CommonErrorCode(String code, String message) {
        this.code = code;
        this.message = message;
    }
}

修改为：
@Getter
public enum UserErrorCode {
    /**
     * 权限异常
     */
    NOT_PERMISSIONS("CLOUD401","您没有操作权限"),
    ;

    private String code;

    private String message;

    UserErrorCode(String code, String message) {
        this.code = code;
        this.message = message;
    }
}

**Comment by purgeyao** [comment]
Thank you for.
