### ISSUE TITLE
默认返回都是text/plain, 如何返回默认就是json呢

### ISSUE THREAD

**Issue by tangyiming** [purgeteam/unified-dispose-springboot#4]
![image](https://user-images.githubusercontent.com/18328731/97104123-5808d980-16ec-11eb-8329-d2138c14d43f.png)

**Comment by purgeyao** [comment]
默认返回的就是json字符串呀

**Comment by tangyiming** [comment]
了解 那就在controller加个produces = "application/json;charset=UTF-8"吧
